<%@ Page Title="Carrito" Language="C#" AutoEventWireup="true" MasterPageFile="~/SiteClientes.Master" CodeBehind="Carrito.aspx.cs" Inherits="Web.Carrito" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-group" style="display: block; position: relative; width: auto; height: auto; margin: 20px auto; background-color: rgba(0,0,0, 0.1); border-radius: 5px; box-shadow: inset 1px 1px 0 0 #d5d7de, inset -1px -1px 0 0 rgba(0,0,0,0.2); background-image: -webkit-radial-gradient(top, circle cover, #4e7a89, #2e3441 80%);">

        <div style="margin-left: 50px;">
            <p style="color: white; font-size: 50px; font-style: oblique; text-align: center">Carrito</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col" style="margin-left: 100px">
                    <asp:GridView ID="dgvCarrito" AutoGenerateColumns="False" AutoGenerateDeleteButton="true" OnRowDeleting="dgvCarrito_RowDeleting" OnRowDataBound="dgvCarrito_RowDataBound" runat="server"  Style="color: white; border-color: white; text-align: center; width: 900px; height: 100px">
                        <Columns>
                            <asp:BoundField HeaderText="Id" DataField="Id" />
                            <asp:BoundField HeaderText="Codigo" DataField="Codigo" />
                            <asp:BoundField HeaderText="Articulo" DataField="Articulo" />
                            <asp:BoundField HeaderText="Cantidad" DataField="Cantidad" />
                            <asp:BoundField HeaderText="Precio Unitario" DataField="Precio Unit" />
                            <asp:BoundField HeaderText="Precio Final" DataField="Precio Final" />

                        </Columns>
                    </asp:GridView>
                </div>
            </div>
            <div class="row" style="margin-left: 100px">
                <div class="col-md-4" style="margin-top: 20px; margin-left: inherit">
                    <asp:Button ID="btnCancelar" runat="server" Text="Cancelar" OnClick="btnCancelar_Click" CssClass="btn btn-outline-secondary" Style="font-size: large; color: white; width: 200px; text-align: center; display: inline-block; margin-bottom: 25px;" />
                </div>
                <div class="col-md-4" style="margin-top: 20px; margin-left: initial">
                    <asp:Button ID="btnComprar" runat="server" Text="Comprar" OnClick="btnComprar_Click" CssClass="btn btn-outline-secondary" Style="font-size: large; color: white; width: 200px; text-align: center; display: inline-block; margin-bottom: 25px;" />
                </div>
            </div>
        </div>
    </div>
</asp:Content>


